# permissions for end users to view kubectlstorageosconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectlstorageosconfig-viewer-role
rules:
- apiGroups:
  - storageos.com
  resources:
  - kubectlstorageosconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storageos.com
  resources:
  - kubectlstorageosconfigs/status
  verbs:
  - get
