# permissions for end users to edit kubectlstorageosconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectlstorageosconfig-editor-role
rules:
- apiGroups:
  - storageos.com
  resources:
  - kubectlstorageosconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storageos.com
  resources:
  - kubectlstorageosconfigs/status
  verbs:
  - get
