apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: StorageOS
spec:
  collectors:
    - logs:
        selector:
          - name=storageos-cluster-operator
        namespace: storageos-operator
        limits:
          maxLines: 10000
    - logs:
        selector:
          - app=storageos
          - app.kubernetes.io/component=storageos-csi-helper
        namespace: kube-system
        limits:
          maxLines: 10000
    - logs:
        selector:
          - app=storageos
          - app.kubernetes.io/component=storageos-daemonset
        namespace: kube-system
        limits:
          maxLines: 10000
    - logs:
        selector:
          - app=storageos
          - app.kubernetes.io/component=storageos-api-manager
        namespace: kube-system
        limits:
          maxLines: 10000
    - logs:
        selector:
          - app=storageos
          - app.kubernetes.io/component=storageos-scheduler
        namespace: kube-system
        limits:
          maxLines: 10000            
    - clusterResources: {}
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.9.0"
              message: StorageOS requires at least Kubernetes 1.9.0 with CSI enabled or later.
              uri: https://kubernetes.io
          - warn:
              when: "< 1.15.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.15.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - customResourceDefinition:
        customResourceDefinitionName: storageosclusters.storageos.com
        outcomes:
          - fail:
              message: The StorageOSCluster CRD was not found in the cluster.
          - pass:
              message: StorageOS CRD is installed and available.
    - nodeResources:
        checkName: Must have at least 3 nodes in the cluster
        outcomes:
          - warn:
              when: "count() < 3"
              message: This application recommends at last 3 nodes.
          - pass:
              message: This cluster has enough nodes.
    - deploymentStatus:
        name: storageos-api-manager
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: The API Manager deployment does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The API Manager deployment has only a single ready replica.
          - pass:
              message: There are multiple replicas of the API Manager deployment ready.
    - deploymentStatus:
        name: storageos-api-manager
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: The API Manager deployment does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The API Manager deployment has only a single ready replica.
          - pass:
              message: There are multiple replicas of the API Manager deployment ready.
    - deploymentStatus:
        name: storageos-csi-helper
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: The CSI helper deployment does not have any ready replicas.
          - pass:
              message: The CSI helper deployment is ready.              
    - deploymentStatus:
        name: storageos-scheduler
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: The scheduler deployment does not have any ready replicas.
          - pass:
              message: The scheduler deployment is ready.                  